<?php
return [
    'project'=>[
        'name'=>'项目管理',
        'link'=>'', 
    ]
    ,
    'activity'=>[ 
        'name'=>'活动管理',
        'link'=>'', 
    ]
    ,
    'channel'=>[ 
        'name'=>'渠道管理',        
        'link'=>'', 
    ]
    ,
    'auditing'=>[ 
        'name'=>'审核',
        'link'=>'', 
    ]
    ,    
    'system'=>[
        'name'=>'系统管理',
        'link'=>'/User',
        'children'=>[
            'user'=>[ 
                'name'=>'用户管理',
                'link'=>'/User',
            ],
            'role'=>[ 
                'name'=>'角色管理',
                'link'=>'/Role',
            ],
            'sms'=>[ 
                'name'=>'短信发送日志',
                'link'=>'/Sms',
            ]
        ]
    ]
];